endpoints:
  enabled: true

logging:
  file: ./logs/filerepository.log
  level:
    Root: WARN
    alex: DEBUG

spring:
  data:
    mongodb:
      authentication-database: frs
      database: frs
      grid-fs-database: frs-grid
      host: songlp.ddns.net
      username: frs
      password: frs
      repositories:
        enabled: true
