server:
  port: 7070
  contextPath: /filerepository/

endpoints:
  enabled: false

spring:
  profiles:
    active: @profileActive@
  messages:
    basename: l10n/exceptions

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-spec.json

info:
  app:
    name: Alex File Repository Service
    description: Alex File Repository Service, which is built on top of Apache Jackrabbit.
    version: @project.version@

repository:
  name: frs

