endpoints:
  enabled: true

logging:
  file: ./logs/filerepository.log
  level:
    Root: WARN
    alex: DEBUG

repository:
  mongo:
    host: songlp.ddns.net
    port: 27017
  config: classpath:repository/repository-dev.xml


