endpoints:
  enabled: true

logging:
  config: classpath:logback/logback-docker.xml

spring:
  data:
    mongodb:
      authentication-database: frs
      database: frs
      host: mongo
      username: frs
      password: frs
      repositories:
        enabled: true
