endpoints:
  enabled: true

logging:
  file: ./logs/filerepository.log
  level:
    Root: WARN
    alex: DEBUG

spring:
  data:
    mongodb:
      authentication-database: frs
      database: frs
      host: localhost
      username: frs
      password: frs
      repositories:
        enabled: true

frs:
  housekeeping:
    enabled: false
