version: '3'
services:
  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - /mongodata:/inlineimage/db
      - ./mongo/mongo-entrypoint:/docker-entrypoint-initdb.d
    command: [--auth]
  filerepository:
    image: alexsong/filerepository:0.0.1
    ports:
      - "31002:7070"
    volumes:
      - /devlogs:/devlogs
      - /lookup:/lookup
    links:
      - mongo
    environment:
      - lookup.dir=file:/lookup
