version: '3'
services:
  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - /mongodata:/data/db
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
    command: [--auth]
